CREATE  DATABASE IF NOT EXISTS game;
USE game;

CREATE TABLE IF NOT EXISTS USERS(
ID INT PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR(20) NOT NULL,
EMAIL VARCHAR(20) NOT NULL,
PASSWORD VARCHAR(255) NOT NULL,
STATUS INT NOT NULL 
);
INSERT INTO USERS(NAME,EMAIL,PASSWORD,STATUS) 
VALUES
('SERGEY','SERGEY@MAIL.RU','32RFCV',1),
('ANDREY','ANDREY@MAIL.RU','32RFCV',0);

UPDATE USERS SET NAME = 'PAVEL' WHERE STATUS=1;
SELECT * FROM USERS WHERE STATUS =0;
SELECT * FROM USERS;
DELETE FROM USERS WHERE EMAIL='SERGEY@MAIL.RU';

-- 12. Произвести добавление, обновление, удаление и чтение даннных из таблицы
-- users
-- Создайте БД game. В БД game сформулируйте SQL запрос для создания таблицы
-- users. Структура таблицы users:
-- Id INT PK AUTO_INCREMENT
-- Name VARCHAR(20) NOT NULL
-- Email VARCHAR(40) NOT NULL
-- Password VARCHAR(255) NOT NULL
-- Status INT NOT NULL
