-- 1. Разработать БД Магазина включающий 4 таблицы


CREATE DATABASE IF NOT EXISTS PART3;

USE part3;

CREATE TABLE IF NOT EXISTS users(
ID INT PRIMARY KEY AUTO_INCREMENT,
`NAME` VARCHAR(25),
EMAIL VARCHAR(30) UNIQUE,
PASSWORD  VARCHAR(255),
DATEREGISTRATION DATETIME DEFAULT CURRENT_TIMESTAMP
); 


CREATE TABLE IF NOT EXISTS Orders(
ID INT PRIMARY KEY AUTO_INCREMENT,
UsersID INT NOT NULL,
ProductsID INT NOT NULL,
DATEORDER DATETIME DEFAULT CURRENT_TIMESTAMP,
STATUSPURCHASE VARCHAR(30),
FOREIGN KEY (UsersID)  REFERENCES users (ID),
FOREIGN KEY (ProductsID) REFERENCES Products(ID)
); 


CREATE TABLE IF NOT EXISTS Products(
ID INT PRIMARY KEY AUTO_INCREMENT,
CategoriesID INT NOT NULL,
NAMEPRODUCTS VARCHAR(30),
DESCRIPTIONS VARCHAR(120),
PRICE DECIMAL,
FOREIGN KEY(CategoriesID) REFERENCES Categories(ID)
); 


CREATE TABLE IF NOT EXISTS Categories(
ID INT PRIMARY KEY AUTO_INCREMENT,
NAMECategories VARCHAR(30)
); 




INSERT INTO users(`NAME`,EMAIL,PASSWORD) VALUES("Artyom","Artyom@mail.ru","1234");
INSERT INTO users(`NAME`,EMAIL,PASSWORD) VALUES("Petr","Petr@mail.ru","1234");


INSERT INTO Categories(NAMECategories) VALUES('technique');
INSERT INTO Categories(NAMECategories) VALUES('FURNITURE');

INSERT INTO Products(CategoriesID,NAMEPRODUCTS,DESCRIPTIONS,PRICE) VALUES(1,'LAPTOP','THIS IS THE BEST LAPTOP',100);
INSERT INTO Products(CategoriesID,NAMEPRODUCTS,DESCRIPTIONS,PRICE) VALUES(2,'Table','comfortable table',50);


INSERT INTO Orders(UsersID,ProductsID,STATUSPURCHASE) VALUES(1,1,"новый");
INSERT INTO Orders(UsersID,ProductsID,STATUSPURCHASE) VALUES(2,2,"новый");

START TRANSACTION;
INSERT INTO Orders(UsersID,ProductsID,STATUSPURCHASE) VALUES(2,1,"новый");
COMMIT;


SELECT * FROM users;
SELECT * FROM Categories;
SELECT * FROM Products;
SELECT * FROM Orders;