-- 1. Разработать БД Магазина включающий 4 таблицы

USE part2;

CREATE TABLE IF NOT EXISTS users(
ID INT PRIMARY KEY AUTO_INCREMENT,
`NAME` VARCHAR(25),
EMAIL VARCHAR(30) UNIQUE,
PASSWORD  VARCHAR(255),
DATEREGISTRATION DATE DEFAULT NOW()
); 


CREATE TABLE IF NOT EXISTS Orders(
ID INT PRIMARY KEY AUTO_INCREMENT,
UsersID INT NOT NULL,
ProductsID INT NOT NULL,
DATEORDER DATE,
STATUSPURCHASE VARCHAR(30),
FOREIGN KEY (UsersID)  REFERENCES users (ID),
FOREIGN KEY (ProductsID) REFERENCES Products(ID)
); 


CREATE TABLE IF NOT EXISTS Products(
ID INT PRIMARY KEY AUTO_INCREMENT,
CategoriesID INT NOT NULL,
NAMEPRODUCTS VARCHAR(30),
DESCRIPTIONS VARCHAR(120),
PRICE DECIMAL,
FOREIGN KEY(CategoriesID) REFERENCES Categories(ID)
); 


CREATE TABLE IF NOT EXISTS Categories(
ID INT PRIMARY KEY AUTO_INCREMENT,
NAMECategories VARCHAR(30)
); 
