CREATE  DATABASE IF NOT EXISTS game;
USE game;

CREATE TABLE IF NOT EXISTS USERS(
ID INT PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR(20) NOT NULL,
EMAIL VARCHAR(20) NOT NULL,
PASSWORD VARCHAR(255) NOT NULL,
STATUS INT NOT NULL 
);



-- Создайте БД game. В БД game сформулируйте SQL запрос для создания таблицы
-- users. Структура таблицы users:
Id INT PK AUTO_INCREMENT
Name VARCHAR(20) NOT NULL
Email VARCHAR(40) NOT NULL
Password VARCHAR(255) NOT NULL
Status INT NOT NULL
